### ISSUE TITLE
iOS 15 compatibility

### ISSUE THREAD

**Issue by scotthmusson** [ImpacGroup/Cordova-Plugin-Tracking-Transparency#2]
I don't see the dialog on iOS 15, works fine on iOS 14.8.

**Comment by ImpacGroup** [comment]
Hi Scott,

thank you for your report. 
We did not yet check the plugin for iOS 15. 
But we will analyze the issue shortly.

**Comment by ImpacGroup** [comment]
Hi Scott,

could you please show use your implementation of the plugin.
We could not produce your issue. In our tests the dialog appears as is should on iOS 15.

**Comment by scotthmusson** [comment]
Absolutely, I will provide a sample for you, might take a day or two. Thanks

**Comment by scotthmusson** [comment]
I would like to withdraw this issue, it is my mistake, sorry for the issue.
