### ISSUE TITLE
XCode error: Value for SWIFT_VERSION cannot be empty.

### ISSUE THREAD

**Issue by orhan-swe** [ImpacGroup/Cordova-Plugin-Tracking-Transparency#6]
After adding the project I am receiving following error in XCode when building the project:

Value for SWIFT_VERSION cannot be empty.

I am using XCode version 13.4.1

If I close the workspace and open it again I get this error on opening of XCode:
"
Unsupported Swift Version
The target “Pjama” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.
Use Xcode 10.1 to migrate the code to Swift 4.
"

I am using several other plugins and only after adding this plugin am I getting this error. What can we do here?

**Comment by rsvagle** [comment]
I'm getting the same error after trying to install this plugin

**Comment by anton-gustafsson** [comment]
Try adding SwiftVersion and deployment-target to your iOS config in config.xml

Example:
```xml
<platform name="ios">


        <preference name="deployment-target" value="12.0" />
        <preference name="SwiftVersion" value="5.3" />
</platform>
```

Maybe this can help?

**Comment by orhan-swe** [comment]
This was solved, unfortunately I do not remember how.
